"""create_projects_module_tables

Revision ID: 617db08d30b7
Revises: 00001_create_recurrence_tables
Create Date: 2026-09-18 08:12:40.033856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617db08d30b7'
down_revision: Union[str, Sequence[str], None] = '00001_create_recurrence_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_checklist_template_org_name')
    )
    op.create_table('workflow_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_entity', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_workflow_template_org_name')
    )
    op.create_table('checklist_template_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('default_workflow_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_workflow_id'], ['workflow_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_project_type_org_code'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_project_type_org_name')
    )
    op.create_table('work_order_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('default_workflow_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_workflow_id'], ['workflow_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_work_order_type_org_code'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_work_order_type_org_name')
    )
    op.create_table('workflow_stage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('allowed_transitions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_workflow_stage_name'),
    sa.UniqueConstraint('workflow_id', 'position', name='uq_workflow_stage_position')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('project_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('current_stage_id', sa.UUID(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('planned_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('sales_quote_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_center.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id', 'organization_id'], ['business_document.id', 'business_document.organization_id'], name='fk_project_document_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_quote_id'], ['sales_quote.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_project_document'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_project_id_org'),
    sa.UniqueConstraint('organization_id', 'project_number', name='uq_project_org_number')
    )
    op.create_index('ix_project_org_status', 'project', ['organization_id', 'status'], unique=False)
    op.create_index('ix_project_org_type', 'project', ['organization_id', 'project_type_id'], unique=False)
    op.create_index(op.f('ix_project_project_number'), 'project', ['project_number'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_user')
    )
    op.create_table('project_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_stage_id', sa.UUID(), nullable=True),
    sa.Column('to_stage_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['workflow_stage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['workflow_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_stage_history_project', 'project_stage_history', ['project_id', 'created_at'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_type_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('current_stage_id', sa.UUID(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['workflow_stage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id', 'organization_id'], ['business_document.id', 'business_document.organization_id'], name='fk_work_order_document_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_type_id'], ['work_order_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'organization_id'], ['project.id', 'project.organization_id'], name='fk_work_order_project_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_work_order_document'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_work_order_id_org'),
    sa.UniqueConstraint('organization_id', 'order_number', name='uq_work_order_org_number')
    )
    op.create_index(op.f('ix_work_order_order_number'), 'work_order', ['order_number'], unique=False)
    op.create_index('ix_work_order_org_status', 'work_order', ['organization_id', 'status'], unique=False)
    op.create_index('ix_work_order_project', 'work_order', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_order_status'), 'work_order', ['status'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('task_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id', 'organization_id'], ['business_document.id', 'business_document.organization_id'], name='fk_task_document_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_task_document'),
    sa.UniqueConstraint('organization_id', 'task_number', name='uq_task_org_number')
    )
    op.create_index('ix_task_org_status', 'task', ['organization_id', 'status'], unique=False)
    op.create_index('ix_task_project', 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task_number'), 'task', ['task_number'], unique=False)
    op.create_index('ix_task_work_order', 'task', ['work_order_id'], unique=False)
    op.create_table('checklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('checked_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('issue_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'issue_number', name='uq_issue_org_number')
    )
    op.create_index(op.f('ix_issue_issue_number'), 'issue', ['issue_number'], unique=False)
    op.create_index('ix_issue_org_status', 'issue', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_issue_status'), 'issue', ['status'], unique=False)
    op.create_table('task_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_assignment_user')
    )
    op.create_table('task_dependency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dependent_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dependent_task_id <> dependency_task_id', name='ck_task_dependency_not_self'),
    sa.ForeignKeyConstraint(['dependency_task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependent_task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependent_task_id', 'dependency_task_id', name='uq_task_dependency_pair')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_issue', 'comment', ['issue_id'], unique=False)
    op.create_index('ix_comment_project', 'comment', ['project_id'], unique=False)
    op.create_index('ix_comment_task', 'comment', ['task_id'], unique=False)
    op.create_index('ix_comment_work_order', 'comment', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_business_document_category'), 'business_document', ['category'], unique=False)
    op.alter_column('contact', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=True)
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_index(op.f('ix_contact_full_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_organization_id'), table_name='contact')
    op.create_index(op.f('ix_contact_document'), 'contact', ['document'], unique=False)
    op.alter_column('customer', 'person_type',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'PJ'::character varying"))
    op.alter_column('customer', 'address_state',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('customer', 'credit_limit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_index(op.f('ix_customer_organization_id'), table_name='customer')
    op.drop_constraint(op.f('uq_customer_org_document'), 'customer', type_='unique')
    op.create_index(op.f('ix_customer_person_type'), 'customer', ['person_type'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_customer_id'), 'customer_product_recurrence', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_last_purchase_date'), 'customer_product_recurrence', ['last_purchase_date'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_organization_id'), 'customer_product_recurrence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_predicted_next_purchase_date'), 'customer_product_recurrence', ['predicted_next_purchase_date'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_product_id'), 'customer_product_recurrence', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_product_recurrence_recurrence_status'), 'customer_product_recurrence', ['recurrence_status'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_customer_id'), 'customer_purchase_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_organization_id'), 'customer_purchase_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_product_id'), 'customer_purchase_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_purchase_history_purchase_date'), 'customer_purchase_history', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_intelligent_replenishment_suggestion_organization_id'), 'intelligent_replenishment_suggestion', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intelligent_replenishment_suggestion_product_id'), 'intelligent_replenishment_suggestion', ['product_id'], unique=False)
    op.create_index(op.f('ix_intelligent_replenishment_suggestion_status'), 'intelligent_replenishment_suggestion', ['status'], unique=False)
    op.create_index(op.f('ix_intelligent_replenishment_suggestion_urgency_level'), 'intelligent_replenishment_suggestion', ['urgency_level'], unique=False)
    op.drop_index(op.f('ix_invoice_item_order_item'), table_name='invoice_item')
    op.drop_index(op.f('ix_invoice_item_org_invoice'), table_name='invoice_item')
    op.drop_index(op.f('ix_payable_org_classification'), table_name='payable')
    op.alter_column('pos_cash_movement', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_pos_cash_movement_session'), table_name='pos_cash_movement')
    op.drop_index(op.f('ix_pos_sale_document'), table_name='pos_sale')
    op.alter_column('price_table', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('price_table_item', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.create_index(op.f('ix_product_demand_forecast_organization_id'), 'product_demand_forecast', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_demand_forecast_product_id'), 'product_demand_forecast', ['product_id'], unique=False)
    op.drop_index(op.f('ix_receivable_customer_id'), table_name='receivable')
    op.create_index(op.f('ix_recurrence_alert_customer_id'), 'recurrence_alert', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recurrence_alert_expected_purchase_date'), 'recurrence_alert', ['expected_purchase_date'], unique=False)
    op.create_index(op.f('ix_recurrence_alert_opportunity_id'), 'recurrence_alert', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recurrence_alert_organization_id'), 'recurrence_alert', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recurrence_alert_product_id'), 'recurrence_alert', ['product_id'], unique=False)
    op.create_index(op.f('ix_recurrence_alert_status'), 'recurrence_alert', ['status'], unique=False)
    op.alter_column('sales_goal', 'seller_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('sales_goal', 'target_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_sales_goal_org_user_month_year'), 'sales_goal', type_='unique')
    op.alter_column('sales_order', 'cancellation_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sales_order_opportunity_id'), table_name='sales_order')
    op.alter_column('sales_quote', 'cancellation_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sales_quote_opportunity_id'), table_name='sales_quote')
    op.alter_column('sales_return', 'return_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'DEVOLUCAO'::character varying"))
    op.alter_column('sales_return', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'COMPLETED'::character varying"))
    op.alter_column('sales_return', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('sales_return', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_sales_return_document'), table_name='sales_return')
    op.alter_column('sales_return_item', 'quantity',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('sales_return_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('sales_return_item', 'total_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_return_item', 'condition',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'GOOD'::character varying"))
    op.alter_column('stock_movement', 'reference_doc',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_movement_product_id'), table_name='stock_movement')
    op.drop_index(op.f('ix_team_organization_id'), table_name='team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_organization_id'), 'team', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_movement_product_id'), 'stock_movement', ['product_id'], unique=False)
    op.alter_column('stock_movement', 'reference_doc',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sales_return_item', 'condition',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'GOOD'::character varying"))
    op.alter_column('sales_return_item', 'total_price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('sales_return_item', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('sales_return_item', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=False)
    op.create_index(op.f('ix_sales_return_document'), 'sales_return', ['organization_id', 'document_id'], unique=False)
    op.alter_column('sales_return', 'reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sales_return', 'total_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('sales_return', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'COMPLETED'::character varying"))
    op.alter_column('sales_return', 'return_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'DEVOLUCAO'::character varying"))
    op.create_index(op.f('ix_sales_quote_opportunity_id'), 'sales_quote', ['opportunity_id'], unique=False)
    op.alter_column('sales_quote', 'cancellation_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_sales_order_opportunity_id'), 'sales_order', ['opportunity_id'], unique=False)
    op.alter_column('sales_order', 'cancellation_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_sales_goal_org_user_month_year'), 'sales_goal', ['organization_id', 'user_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.alter_column('sales_goal', 'target_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('sales_goal', 'seller_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_recurrence_alert_status'), table_name='recurrence_alert')
    op.drop_index(op.f('ix_recurrence_alert_product_id'), table_name='recurrence_alert')
    op.drop_index(op.f('ix_recurrence_alert_organization_id'), table_name='recurrence_alert')
    op.drop_index(op.f('ix_recurrence_alert_opportunity_id'), table_name='recurrence_alert')
    op.drop_index(op.f('ix_recurrence_alert_expected_purchase_date'), table_name='recurrence_alert')
    op.drop_index(op.f('ix_recurrence_alert_customer_id'), table_name='recurrence_alert')
    op.create_index(op.f('ix_receivable_customer_id'), 'receivable', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_product_demand_forecast_product_id'), table_name='product_demand_forecast')
    op.drop_index(op.f('ix_product_demand_forecast_organization_id'), table_name='product_demand_forecast')
    op.alter_column('price_table_item', 'price',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('price_table', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_pos_sale_document'), 'pos_sale', ['organization_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_pos_cash_movement_session'), 'pos_cash_movement', ['pos_session_id'], unique=False)
    op.alter_column('pos_cash_movement', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_payable_org_classification'), 'payable', ['organization_id', 'obligation_type', 'business_origin'], unique=False)
    op.create_index(op.f('ix_invoice_item_org_invoice'), 'invoice_item', ['organization_id', 'invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_item_order_item'), 'invoice_item', ['sales_order_item_id'], unique=False)
    op.drop_index(op.f('ix_intelligent_replenishment_suggestion_urgency_level'), table_name='intelligent_replenishment_suggestion')
    op.drop_index(op.f('ix_intelligent_replenishment_suggestion_status'), table_name='intelligent_replenishment_suggestion')
    op.drop_index(op.f('ix_intelligent_replenishment_suggestion_product_id'), table_name='intelligent_replenishment_suggestion')
    op.drop_index(op.f('ix_intelligent_replenishment_suggestion_organization_id'), table_name='intelligent_replenishment_suggestion')
    op.drop_index(op.f('ix_customer_purchase_history_purchase_date'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_purchase_history_product_id'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_purchase_history_organization_id'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_purchase_history_customer_id'), table_name='customer_purchase_history')
    op.drop_index(op.f('ix_customer_product_recurrence_recurrence_status'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_product_recurrence_product_id'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_product_recurrence_predicted_next_purchase_date'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_product_recurrence_organization_id'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_product_recurrence_last_purchase_date'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_product_recurrence_customer_id'), table_name='customer_product_recurrence')
    op.drop_index(op.f('ix_customer_person_type'), table_name='customer')
    op.create_unique_constraint(op.f('uq_customer_org_document'), 'customer', ['organization_id', 'document'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_customer_organization_id'), 'customer', ['organization_id'], unique=False)
    op.alter_column('customer', 'credit_limit',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('customer', 'address_state',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('customer', 'person_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'PJ'::character varying"))
    op.drop_index(op.f('ix_contact_document'), table_name='contact')
    op.create_index(op.f('ix_contact_organization_id'), 'contact', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contact_full_name'), 'contact', ['full_name'], unique=False)
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.alter_column('contact', 'full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_business_document_category'), table_name='business_document')
    op.drop_index('ix_comment_work_order', table_name='comment')
    op.drop_index('ix_comment_task', table_name='comment')
    op.drop_index('ix_comment_project', table_name='comment')
    op.drop_index('ix_comment_issue', table_name='comment')
    op.drop_table('comment')
    op.drop_table('checklist_item')
    op.drop_table('task_dependency')
    op.drop_table('task_assignment')
    op.drop_index(op.f('ix_issue_status'), table_name='issue')
    op.drop_index('ix_issue_org_status', table_name='issue')
    op.drop_index(op.f('ix_issue_issue_number'), table_name='issue')
    op.drop_table('issue')
    op.drop_table('checklist')
    op.drop_index('ix_task_work_order', table_name='task')
    op.drop_index(op.f('ix_task_task_number'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index('ix_task_project', table_name='task')
    op.drop_index('ix_task_org_status', table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_work_order_status'), table_name='work_order')
    op.drop_index('ix_work_order_project', table_name='work_order')
    op.drop_index('ix_work_order_org_status', table_name='work_order')
    op.drop_index(op.f('ix_work_order_order_number'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index('ix_project_stage_history_project', table_name='project_stage_history')
    op.drop_table('project_stage_history')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_project_number'), table_name='project')
    op.drop_index('ix_project_org_type', table_name='project')
    op.drop_index('ix_project_org_status', table_name='project')
    op.drop_table('project')
    op.drop_table('workflow_stage')
    op.drop_table('work_order_type')
    op.drop_table('project_type')
    op.drop_table('checklist_template_item')
    op.drop_table('workflow_template')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
