"""add_financial_and_reception_fields_to_purchase_order

Revision ID: 8b74bfedd476
Revises: ab3e2b8258bf
Create Date: 2026-08-15 22:42:45.850593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b74bfedd476'
down_revision: Union[str, Sequence[str], None] = 'ab3e2b8258bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('purchase_order', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('purchase_order', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('purchase_order', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_order', sa.Column('received_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchase_order', 'user', ['received_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'received_by_id')
    op.drop_column('purchase_order', 'received_at')
    op.drop_column('purchase_order', 'invoice_number')
    op.drop_column('purchase_order', 'discount_amount')
    op.drop_column('purchase_order', 'freight_amount')
    # ### end Alembic commands ###
