"""add_traceability_and_stock_fields_to_product

Revision ID: ab3e2b8258bf
Revises: 338e79d7acff
Create Date: 2026-08-15 22:30:28.460896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3e2b8258bf'
down_revision: Union[str, Sequence[str], None] = '338e79d7acff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('ncm', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('is_perishable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('product', sa.Column('requires_batch', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('product', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('min_stock', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('product', sa.Column('max_stock', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('product', sa.Column('storage_location', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_column('product', 'storage_location')
    op.drop_column('product', 'max_stock')
    op.drop_column('product', 'min_stock')
    op.drop_column('product', 'shelf_life_days')
    op.drop_column('product', 'requires_batch')
    op.drop_column('product', 'is_perishable')
    op.drop_column('product', 'ncm')
    op.drop_column('product', 'barcode')
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###
