"""add_quotation_and_supplier_quotes_tables

Revision ID: f54882fa6455
Revises: 8b74bfedd476
Create Date: 2026-08-15 22:56:32.953586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54882fa6455'
down_revision: Union[str, Sequence[str], None] = '8b74bfedd476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_process',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purchase_request_id', sa.UUID(), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_request_id')
    )
    op.create_index(op.f('ix_quotation_process_quotation_number'), 'quotation_process', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotation_process_status'), 'quotation_process', ['status'], unique=False)
    op.create_table('supplier_quote',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('quotation_process_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('quote_reference', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('freight_type', sa.String(length=50), nullable=True),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_process_id'], ['quotation_process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quote_status'), 'supplier_quote', ['status'], unique=False)
    op.create_table('supplier_quote_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_quote_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('brand_offered', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_quote_id'], ['supplier_quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase_order', sa.Column('supplier_quote_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchase_order', 'supplier_quote', ['supplier_quote_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'supplier_quote_id')
    op.drop_table('supplier_quote_item')
    op.drop_index(op.f('ix_supplier_quote_status'), table_name='supplier_quote')
    op.drop_table('supplier_quote')
    op.drop_index(op.f('ix_quotation_process_status'), table_name='quotation_process')
    op.drop_index(op.f('ix_quotation_process_quotation_number'), table_name='quotation_process')
    op.drop_table('quotation_process')
    # ### end Alembic commands ###
